// 登場人物。見た目（look）・強さ・セリフをまとめて定義する。

export const PLAYER_LOOK = {
  skin: '#f2c9a9',
  hair: { style: 'neat', color: '#2a2320' },
  top: { type: 'suit', color: '#27345a' },
  shirt: '#f7f9fc',
  tie: '#e0402f',
  bottom: { type: 'pants', color: '#1f2940' },
  shoes: '#2a1d17',
  brows: 'normal',
  cheeks: true,
};

export const CAST = {
  senpai: {
    code: 1,
    name: '佐藤先輩',
    role: '営業2課',
    nick: 'ちょっといい先輩',
    trait: '近くを通ると「ちょっといい？」。5分で終わったためしがない。',
    power: 2,
    penalty: 15,
    papers: 0,
    stamp: '5分だけ',
    tint: '#f0a23b',
    voice: { freq: 180, type: 'triangle' },
    look: {
      skin: '#eebd98',
      hair: { style: 'side', color: '#3a2c24' },
      top: { type: 'cardigan', color: '#9b7b5c' },
      shirt: '#eef3f8',
      tie: '#3b5a86',
      bottom: { type: 'pants', color: '#4b4f5a' },
      shoes: '#3a2a20',
      glasses: { color: '#2b2b2b' },
      brows: 'normal',
      cheeks: true,
      width: 1.12,
      prop: { right: 'mug' },
    },
    notice: ['ちょっといい？', 'あ、ちょうどよかった！', 'ねぇねぇ、今いい？', '5分だけ！'],
    giveup: ['…まあ、あとでいっか', '忙しそうだな〜', 'また今度ね〜'],
    after: ['いや〜助かったよ！', 'じゃ、また続きは今度！'],
    talks: [
      ['ちょっといい？ 5分だけ！', '先週のゴルフの話なんだけどさ、3番ホールで…', '（15分経過）…で、そのバンカーがさぁ'],
      ['ちょっといい？ 来期の予算の件、軽くでいいから', '…ってのは前置きで、実は娘の受験がさ', '（15分経過）まあ、そういうことだから！'],
      ['ねぇねぇ、競合のプレゼンの噂聞いた？', '聞いてない？ならいいんだけど、実はね…', '（15分経過）ここだけの話だからね！'],
      ['あ、ちょうどよかった！ 5分だけ！', '最近ハマってるサウナの話なんだけど', '（15分経過）…ととのうって、そういうことなんだよ'],
    ],
  },

  keiri: {
    code: 2,
    name: '細田さん',
    role: '経理部',
    nick: '経理の鬼',
    trait: '赤い視界に入ると猛ダッシュ。近づかれると足がすくむ。社内最強。',
    power: 5,
    penalty: 20,
    papers: 2,
    stamp: '差し戻し',
    tint: '#e0402f',
    voice: { freq: 540, type: 'square' },
    look: {
      skin: '#f5d2bb',
      hair: { style: 'bun', color: '#1f1a1a' },
      top: { type: 'vest', color: '#2b3a67' },
      shirt: '#ffffff',
      ribbon: '#c7372b',
      bottom: { type: 'skirt', color: '#2b3a67' },
      legs: '#caa287',
      shoes: '#1b1b1b',
      glasses: { color: '#c0302a', square: true },
      brows: 'angry',
      cheeks: false,
      scale: 0.96,
      prop: { left: 'clipboard', right: 'redpen' },
    },
    notice: ['ちょっと！！', 'そこの営業さん！！', '待ちなさい！！', '見つけましたよ！！'],
    giveup: ['……次は逃がしませんから', '経費精算、今日締めですからね', '……チッ'],
    after: ['以上です。', '今日中にお願いしますね。'],
    talks: [
      ['ちょっと！この領収書、但し書きが「お品代」なんですけど？', 'それとホチキスは左上45度って言いましたよね？', '今日中に再提出でお願いします。'],
      ['交通費、ICカードの履歴と1円合いません。', '1円でも、合わないものは合わないんです。', '明細、全部出し直してください。'],
      ['会議費の参加者、「他3名」じゃ通りません。', '全員フルネームで、役職も。', 'はい、これ修正依頼です。'],
      ['この日付、令和と西暦が混ざってます。', 'あとフォント、明朝とゴシックが混在してますね。', '揃えてから持ってきてください。'],
    ],
  },

  shorui: {
    code: 3,
    name: '山本部長代理',
    role: '総務部',
    nick: '書類おじさん',
    trait: '遠くから書類を投げてくる。当たると頭に積もって足が重くなる。シュレッダーで捨てられる。',
    power: 2,
    penalty: 2,
    papers: 1,
    stamp: '至急',
    tint: '#6f8fb3',
    voice: { freq: 150, type: 'sawtooth' },
    look: {
      skin: '#e8b48f',
      hair: { style: 'bald', color: '#6d625b' },
      top: { type: 'shirt', color: '#dfe8f3' },
      shirt: '#dfe8f3',
      tie: '#7a4a3a',
      suspenders: '#7a3b33',
      bottom: { type: 'pants', color: '#5a5347' },
      shoes: '#2d241f',
      mustache: '#5a4f48',
      brows: 'normal',
      cheeks: true,
      width: 1.18,
      prop: { left: 'papers' },
    },
    notice: ['おっ、ちょうどいい！'],
    throwLines: ['これもお願い！', 'ついでにこれも！', '目を通しといて〜', 'ハンコだけでいいから！', '至急じゃないけど至急で！', '回覧です〜！'],
    talks: [['おっ、ちょうどよかった', 'これ全部、今日中にハンコよろしく！']],
  },

  mtg: {
    code: 4,
    name: '黒木課長',
    role: '企画部',
    nick: 'MTG入れたがり課長',
    trait: 'フロアを巡回中。黄色い視界に入ると「30分だけMTG」が始まる。',
    power: 4,
    penalty: 30,
    papers: 0,
    stamp: 'MTG招集',
    tint: '#ffcf3a',
    voice: { freq: 130, type: 'triangle' },
    look: {
      skin: '#efc3a3',
      hair: { style: 'slick', color: '#161412' },
      top: { type: 'suit', color: '#2d2f35' },
      shirt: '#cfe0f5',
      tie: '#f2b632',
      bottom: { type: 'pants', color: '#2d2f35' },
      shoes: '#111111',
      brows: 'normal',
      cheeks: false,
      scale: 1.05,
      prop: { left: 'laptop' },
    },
    notice: ['お、ちょうどいい！', 'いたいた！', 'ちょっと時間ある？'],
    giveup: ['…じゃあ招待だけ送っとくね', 'カレンダー空けといて〜'],
    after: ['いい議論だった！', 'じゃ、次回もよろしく！'],
    talks: [
      ['今から30分だけMTGいい？', 'アジェンダは…今から一緒に考えよう！', '（2時間後）じゃ、論点整理は次回までに。'],
      ['ちょっとブレストしたいんだよね', 'ホワイトボードある部屋、もう取ってあるから', '（2時間後）いい議論だった！結論は次回！'],
      ['認識合わせ、5分だけ！', '…の前に、背景から話すね', '（2時間後）じゃ、議事録よろしく！'],
    ],
  },

  shinjin: {
    code: 5,
    name: '若葉くん',
    role: '営業部 新人',
    nick: '質問魔の新人',
    trait: 'ついてきて「せんぱ〜い！」と叫び、周りの人を呼び寄せる。ダッシュで振り切ると転ぶ。',
    power: 3,
    penalty: 0,
    papers: 0,
    stamp: '',
    tint: '#3aa56c',
    voice: { freq: 420, type: 'sine' },
    look: {
      skin: '#f6d3b8',
      hair: { style: 'spiky', color: '#3a2a1e' },
      top: { type: 'suit', color: '#39424f' },
      shirt: '#ffffff',
      tie: '#2f8f5b',
      bottom: { type: 'pants', color: '#39424f' },
      shoes: '#1e1e1e',
      brows: 'worried',
      cheeks: true,
      scale: 0.93,
      badge: 'wakaba',
      prop: { left: 'notebook' },
    },
    notice: ['先輩！！', 'あっ先輩！おつかれさまです！', '先輩〜！'],
    shouts: ['せんぱ〜い！', '先輩！質問いいですか！', '先輩どこ行くんですか〜！', 'メモ取らせてください！', '先輩！待ってください〜！'],
    trip: ['あっ…！', 'うわっ', 'ぶへっ'],
    giveup: ['メモしときます！', 'あとで聞きます！'],
  },

  kanji: {
    code: 6,
    name: '宴田さん',
    role: '広報部',
    nick: '飲み会幹事',
    trait: '出口の前で通せんぼ。上下に揺さぶって、ダッシュですり抜けろ。',
    power: 3,
    penalty: 20,
    papers: 0,
    stamp: '出席',
    tint: '#ff7a59',
    voice: { freq: 260, type: 'square' },
    look: {
      skin: '#f0bf9a',
      hair: { style: 'short', color: '#4a3020' },
      top: { type: 'shirt', color: '#fbe7c6' },
      shirt: '#fbe7c6',
      tie: null,
      bottom: { type: 'pants', color: '#6b5a48' },
      shoes: '#3a2a1e',
      brows: 'happy',
      cheeks: true,
      blush: true,
      headband: '#d93b30',
      prop: { left: 'list' },
    },
    notice: ['今日来るよね！？'],
    guardLines: ['一次会だけ！', '今日来るよね？', '幹事の顔を立てて！', '会費は当日で！', '二次会もあるよ〜！'],
    after: ['じゃ、19時に駅前ね〜！', '出席で丸しとく！'],
    talks: [
      ['今日来るよね？一次会だけ！', 'ほんと一次会だけだから！', '（二次会の店も、もう予約してある）'],
      ['あ、帰るとこ？ちょうどよかった！', '今日、課の歓迎会でさ！', '出席に丸しとくね〜！'],
    ],
  },
};

export const BOSS = {
  name: '大河原部長',
  role: '営業部長',
  tint: '#1b2340',
  voice: { freq: 110, type: 'triangle' },
  look: {
    skin: '#e9b995',
    hair: { style: 'bald', color: '#8b8580' },
    top: { type: 'suit', color: '#3b3f47' },
    shirt: '#ffffff',
    tie: '#8a1f2b',
    bottom: { type: 'pants', color: '#3b3f47' },
    shoes: '#111111',
    glasses: { color: '#6b5a2a' },
    mustache: '#6d6660',
    brows: 'normal',
    width: 1.25,
    scale: 1.05,
  },
  lines: ['おう、企画書か。', '……うん。いいじゃない。', 'これで行こう。承認！'],
};

export const WORKER_HAIR = ['short', 'side', 'bob', 'long', 'short', 'bald', 'pony', 'neat'];
export const HAIR_COLORS = ['#2a2320', '#3d2b20', '#1b1716', '#5a3b28', '#6d5a4a', '#8a8580', '#2c2420'];
export const SKINS = ['#f2c9a9', '#eebd98', '#f6d7c1', '#e3ae88', '#f0c4a0'];
export const WORKER_TOPS = [
  { type: 'suit', color: '#2f3a55' },
  { type: 'suit', color: '#44474f' },
  { type: 'shirt', color: '#ffffff' },
  { type: 'shirt', color: '#cfe0f5' },
  { type: 'cardigan', color: '#c9b79c' },
  { type: 'cardigan', color: '#7d8f7a' },
  { type: 'shirt', color: '#f5d8d8' },
  { type: 'suit', color: '#1f2226' },
];
