// 登場人物。見た目（look）・強さ・セリフをまとめて定義する。

export const PLAYER_LOOK = {
  skin: '#f2c9a9',
  hair: { style: 'neat', color: '#2a2320' },
  top: { type: 'suit', color: '#27345a' },
  shirt: '#f7f9fc',
  tie: '#e0402f',
  bottom: { type: 'pants', color: '#1f2940' },
  shoes: '#2a1d17',
  brows: 'normal',
  cheeks: true,
};

export const CAST = {
  senpai: {
    code: 1,
    name: '佐藤先輩',
    role: '営業2課',
    nick: 'ちょっといい先輩',
    trait: '近くを通ると「ちょっといい？」。5分で終わったためしがない。',
    power: 2,
    penalty: 15,
    papers: 0,
    stamp: '5分だけ',
    tint: '#f0a23b',
    voice: { freq: 180, type: 'triangle' },
    look: {
      skin: '#eebd98',
      hair: { style: 'side', color: '#3a2c24' },
      top: { type: 'cardigan', color: '#9b7b5c' },
      shirt: '#eef3f8',
      tie: '#3b5a86',
      bottom: { type: 'pants', color: '#4b4f5a' },
      shoes: '#3a2a20',
      glasses: { color: '#2b2b2b' },
      brows: 'normal',
      cheeks: true,
      width: 1.12,
      prop: { right: 'mug' },
    },
    notice: ['ちょっといい？', 'あ、ちょうどよかった！', 'ねぇねぇ、今いい？', '5分だけ！'],
    giveup: ['…まあ、あとでいっか', '忙しそうだな〜', 'また今度ね〜'],
    after: ['いや〜助かったよ！', 'じゃ、また続きは今度！'],
    talks: [
      ['ちょっといい？ 5分だけ！', '先週のゴルフの話なんだけどさ、3番ホールで…', '（15分経過）…で、そのバンカーがさぁ'],
      ['ちょっといい？ 来期の予算の件、軽くでいいから', '…ってのは前置きで、実は娘の受験がさ', '（15分経過）まあ、そういうことだから！'],
      ['ねぇねぇ、競合のプレゼンの噂聞いた？', '聞いてない？ならいいんだけど、実はね…', '（15分経過）ここだけの話だからね！'],
      ['あ、ちょうどよかった！ 5分だけ！', '最近ハマってるサウナの話なんだけど', '（15分経過）…ととのうって、そういうことなんだよ'],
    ],
  },

  keiri: {
    code: 2,
    name: '細田さん',
    role: '経理部',
    nick: '経理の鬼',
    trait: '赤い視界に入ると猛ダッシュ。近づかれると足がすくむ。社内最強。',
    power: 5,
    penalty: 20,
    papers: 2,
    stamp: '差し戻し',
    tint: '#e0402f',
    voice: { freq: 540, type: 'square' },
    look: {
      skin: '#f5d2bb',
      hair: { style: 'bun', color: '#1f1a1a' },
      top: { type: 'vest', color: '#2b3a67' },
      shirt: '#ffffff',
      ribbon: '#c7372b',
      bottom: { type: 'skirt', color: '#2b3a67' },
      legs: '#caa287',
      shoes: '#1b1b1b',
      glasses: { color: '#c0302a', square: true },
      brows: 'angry',
      cheeks: false,
      scale: 0.96,
      prop: { left: 'clipboard', right: 'redpen' },
    },
    notice: ['ちょっと！！', 'そこの営業さん！！', '待ちなさい！！', '見つけましたよ！！'],
    giveup: ['……次は逃がしませんから', '経費精算、今日締めですからね', '……チッ'],
    after: ['以上です。', '今日中にお願いしますね。'],
    talks: [
      ['ちょっと！この領収書、但し書きが「お品代」なんですけど？', 'それとホチキスは左上45度って言いましたよね？', '今日中に再提出でお願いします。'],
      ['交通費、ICカードの履歴と1円合いません。', '1円でも、合わないものは合わないんです。', '明細、全部出し直してください。'],
      ['会議費の参加者、「他3名」じゃ通りません。', '全員フルネームで、役職も。', 'はい、これ修正依頼です。'],
      ['この日付、令和と西暦が混ざってます。', 'あとフォント、明朝とゴシックが混在してますね。', '揃えてから持ってきてください。'],
    ],
  },

  shorui: {
    code: 3,
    name: '山本部長代理',
    role: '総務部',
    nick: '書類おじさん',
    trait: '遠くから書類を投げてくる。当たると頭に積もって足が重くなる。シュレッダーで捨てられる。',
    power: 2,
    penalty: 2,
    papers: 1,
    stamp: '至急',
    tint: '#6f8fb3',
    voice: { freq: 150, type: 'sawtooth' },
    look: {
      skin: '#e8b48f',
      hair: { style: 'bald', color: '#6d625b' },
      top: { type: 'shirt', color: '#dfe8f3' },
      shirt: '#dfe8f3',
      tie: '#7a4a3a',
      suspenders: '#7a3b33',
      bottom: { type: 'pants', color: '#5a5347' },
      shoes: '#2d241f',
      mustache: '#5a4f48',
      brows: 'normal',
      cheeks: true,
      width: 1.18,
      prop: { left: 'papers' },
    },
    notice: ['おっ、ちょうどいい！'],
    throwLines: ['これもお願い！', 'ついでにこれも！', '目を通しといて〜', 'ハンコだけでいいから！', '至急じゃないけど至急で！', '回覧です〜！'],
    talks: [['おっ、ちょうどよかった', 'これ全部、今日中にハンコよろしく！']],
  },

  mtg: {
    code: 4,
    name: '黒木課長',
    role: '企画部',
    nick: 'MTG入れたがり課長',
    trait: 'フロアを巡回中。黄色い視界に入ると「30分だけMTG」が始まる。',
    power: 4,
    penalty: 30,
    papers: 0,
    stamp: 'MTG招集',
    tint: '#ffcf3a',
    voice: { freq: 130, type: 'triangle' },
    look: {
      skin: '#efc3a3',
      hair: { style: 'slick', color: '#161412' },
      top: { type: 'suit', color: '#2d2f35' },
      shirt: '#cfe0f5',
      tie: '#f2b632',
      bottom: { type: 'pants', color: '#2d2f35' },
      shoes: '#111111',
      brows: 'normal',
      cheeks: false,
      scale: 1.05,
      prop: { left: 'laptop' },
    },
    notice: ['お、ちょうどいい！', 'いたいた！', 'ちょっと時間ある？'],
    giveup: ['…じゃあ招待だけ送っとくね', 'カレンダー空けといて〜'],
    after: ['いい議論だった！', 'じゃ、次回もよろしく！'],
    talks: [
      ['今から30分だけMTGいい？', 'アジェンダは…今から一緒に考えよう！', '（2時間後）じゃ、論点整理は次回までに。'],
      ['ちょっとブレストしたいんだよね', 'ホワイトボードある部屋、もう取ってあるから', '（2時間後）いい議論だった！結論は次回！'],
      ['認識合わせ、5分だけ！', '…の前に、背景から話すね', '（2時間後）じゃ、議事録よろしく！'],
    ],
  },

  shinjin: {
    code: 5,
    name: '若葉くん',
    role: '営業部 新人',
    nick: '質問魔の新人',
    trait: 'ついてきて「せんぱ〜い！」と叫び、周りの人を呼び寄せる。ダッシュで振り切ると転ぶ。',
    power: 3,
    penalty: 0,
    papers: 0,
    stamp: '',
    tint: '#3aa56c',
    voice: { freq: 420, type: 'sine' },
    look: {
      skin: '#f6d3b8',
      hair: { style: 'spiky', color: '#3a2a1e' },
      top: { type: 'suit', color: '#39424f' },
      shirt: '#ffffff',
      tie: '#2f8f5b',
      bottom: { type: 'pants', color: '#39424f' },
      shoes: '#1e1e1e',
      brows: 'worried',
      cheeks: true,
      scale: 0.93,
      badge: 'wakaba',
      prop: { left: 'notebook' },
    },
    notice: ['先輩！！', 'あっ先輩！おつかれさまです！', '先輩〜！'],
    shouts: ['せんぱ〜い！', '先輩！質問いいですか！', '先輩どこ行くんですか〜！', 'メモ取らせてください！', '先輩！待ってください〜！'],
    trip: ['あっ…！', 'うわっ', 'ぶへっ'],
    giveup: ['メモしときます！', 'あとで聞きます！'],
  },

  kanji: {
    code: 6,
    name: '宴田さん',
    role: '広報部',
    nick: '飲み会幹事',
    trait: '出口の前で通せんぼ。上下に揺さぶって、ダッシュですり抜けろ。',
    power: 3,
    penalty: 20,
    papers: 0,
    stamp: '出席',
    tint: '#ff7a59',
    voice: { freq: 260, type: 'square' },
    look: {
      skin: '#f0bf9a',
      hair: { style: 'short', color: '#4a3020' },
      top: { type: 'shirt', color: '#fbe7c6' },
      shirt: '#fbe7c6',
      tie: null,
      bottom: { type: 'pants', color: '#6b5a48' },
      shoes: '#3a2a1e',
      brows: 'happy',
      cheeks: true,
      blush: true,
      headband: '#d93b30',
      prop: { left: 'list' },
    },
    notice: ['今日来るよね！？'],
    guardLines: ['一次会だけ！', '今日来るよね？', '幹事の顔を立てて！', '会費は当日で！', '二次会もあるよ〜！'],
    after: ['じゃ、19時に駅前ね〜！', '出席で丸しとく！'],
    talks: [
      ['今日来るよね？一次会だけ！', 'ほんと一次会だけだから！', '（二次会の店も、もう予約してある）'],
      ['あ、帰るとこ？ちょうどよかった！', '今日、課の歓迎会でさ！', '出席に丸しとくね〜！'],
    ],
  },

  shacho: {
    code: 7,
    name: '鶴田社長',
    role: '代表取締役',
    nick: '抜き打ち巡回の社長',
    trait: '金色の視界の中で動くとアウト（ダッシュも見られる）。立ち止まればお辞儀でセーフ。社長の視界では、ほかの人も大人しくなる。',
    power: 5,
    penalty: 25,
    papers: 0,
    stamp: '査定',
    tint: '#d4a82a',
    voice: { freq: 100, type: 'sawtooth' },
    look: {
      skin: '#e8b995',
      hair: { style: 'side', color: '#dcd8d2' },
      top: { type: 'suit', color: '#1c2233' },
      shirt: '#ffffff',
      tie: '#c9a227',
      bottom: { type: 'pants', color: '#1c2233' },
      shoes: '#0d0d0d',
      mustache: '#e4e0da',
      brows: 'normal',
      cheeks: false,
      width: 1.18,
      scale: 1.08,
    },
    notice: ['おや？', 'そこの君！'],
    pass: ['うむ、ご苦労。', '精が出るね。', '顔色いいね。', 'うむ。'],
    talks: [
      ['そこの君、廊下は走らない！', '……で、どこの部署だったかな？', '（25分経過）…わしが若い頃はな、ポケベルで…'],
      ['おや、ちょうどいい。', '今期の数字、ざっくり説明してくれる？', '（25分経過）…続きは来週の面談で聞こう。'],
      ['君、ネクタイが曲がっとるよ。', '身だしなみは営業の基本だ。わしの新人時代は…', '（25分経過）…というわけだ。がんばりたまえ。'],
    ],
  },

  doki: {
    code: 8,
    name: '三上さん',
    role: '営業2課 同期',
    nick: '充電器の同期',
    trait: 'スマホを見ながらうろうろ。目が合うと一直線に走ってくる。「充電器貸して！」',
    power: 2,
    penalty: 10,
    papers: 0,
    stamp: '充電中',
    tint: '#b07ee8',
    voice: { freq: 360, type: 'triangle' },
    look: {
      skin: '#f5d3bd',
      hair: { style: 'pony', color: '#5a3b28' },
      top: { type: 'cardigan', color: '#c9b4ec' },
      shirt: '#ffffff',
      tie: null,
      bottom: { type: 'skirt', color: '#3e4661' },
      legs: '#d8b49a',
      shoes: '#2a2a2a',
      brows: 'worried',
      cheeks: true,
      scale: 0.96,
      prop: { right: 'phone' },
    },
    notice: ['あっ！充電器持ってる！？', 'ねえ、充電器貸して！', 'タイプC！タイプCある！？'],
    giveup: ['…ほかの人に借りよ', 'はぁ、はぁ…速い…'],
    after: ['助かった〜！', '今度おごる！（おごらない）'],
    talks: [
      ['充電器貸して！残り2％なの！', 'え、ライトニング？…じゃあいいや', '（10分経過）でさ、昨日のドラマ見た？'],
      ['ねえ聞いて！充電器忘れた！', 'あとモバイルバッテリーも忘れた！', '（10分経過）…あ、このコンセント使えないやつだ'],
    ],
  },

  warikomi: {
    code: 9,
    name: '石井係長',
    role: '総務部',
    nick: '割り込み係長',
    trait: 'コピー機のまわりをうろうろ。印刷中の人を見つけると遠くからでも寄ってきて「1枚だけ先いい？」。',
    power: 3,
    penalty: 10,
    papers: 0,
    stamp: '割り込み',
    tint: '#8e6cc7',
    voice: { freq: 240, type: 'triangle' },
    look: {
      skin: '#eebd98',
      hair: { style: 'short', color: '#2b2522' },
      top: { type: 'shirt', color: '#e6ecf5' },
      shirt: '#e6ecf5',
      tie: '#6b4fa0',
      bottom: { type: 'pants', color: '#52586a' },
      shoes: '#222222',
      glasses: { color: '#333333', square: true },
      brows: 'worried',
      cheeks: false,
      prop: { left: 'papers' },
    },
    notice: ['あ、それ終わったら1枚だけ！', 'ちょっと先に1枚だけいい？', 'コピー機空いてる？'],
    giveup: ['…じゃあ後でいいや', '急ぎじゃないから（急ぎ）'],
    after: ['ありがとね〜', '助かった！200枚だけだったから'],
    talks: [
      ['ごめん！1枚だけ先にいい？', '（ピー、ガシャン、ガシャン、ガシャン…）', '（10分経過）…ごめん、200枚だった。'],
      ['あ、両面印刷ってどうやるんだっけ？', 'ついでにホチキスの設定も教えて！', '（10分経過）あ、トナー切れた。'],
    ],
  },

  // ---------------------------------------------------------------- 社外（第4章）
  tissue: {
    code: 10,
    behavior: 'handout',
    name: 'ティッシュ配りの人',
    role: '駅前',
    nick: 'ティッシュ配り',
    trait: '近くを通ると、ティッシュとチラシを渡してくる。受け取ると頭に積もる。ダッシュで通り過ぎればOK。',
    power: 1,
    penalty: 1,
    papers: 1,
    stamp: '配布',
    tint: '#3fb6a8',
    voice: { freq: 330, type: 'triangle' },
    look: {
      skin: '#f2c6a6',
      hair: { style: 'short', color: '#3a2a1e' },
      top: { type: 'shirt', color: '#3fb6a8' },
      shirt: '#3fb6a8',
      tie: null,
      bottom: { type: 'pants', color: '#2d3240' },
      shoes: '#222222',
      headband: '#ffffff',
      brows: 'happy',
      cheeks: true,
      prop: { right: 'papers' },
    },
    notice: ['よろしくお願いしまーす！'],
    talks: [['よろしくお願いしまーす！', '新規オープンです〜！']],
  },
  survey: {
    code: 11,
    behavior: 'senpai',
    tune: { notice: 3.3, chase: 4.3, chaseMax: 2.2, lose: 7, cooldown: 8 },
    name: '調査員さん',
    role: '街頭アンケート',
    nick: '街頭アンケート',
    trait: '「ちょっとお時間いいですか？」目が合うと短く猛ダッシュしてくる。すぐあきらめる。',
    power: 2,
    penalty: 10,
    papers: 0,
    stamp: '回答済',
    tint: '#ff9f43',
    voice: { freq: 380, type: 'sine' },
    look: {
      skin: '#f6d3bd',
      hair: { style: 'bob', color: '#6b4a32' },
      top: { type: 'vest', color: '#ff9f43' },
      shirt: '#ffffff',
      ribbon: null,
      bottom: { type: 'pants', color: '#3e4661' },
      shoes: '#2a2a2a',
      brows: 'happy',
      cheeks: true,
      scale: 0.95,
      prop: { left: 'clipboard' },
    },
    notice: ['ちょっとお時間いいですか？', '1分だけ！1分だけ！', 'アンケートにご協力を〜！'],
    giveup: ['…あ、次の方〜', 'また今度〜'],
    after: ['ご協力ありがとうございました！', '粗品のボールペンです！'],
    talks: [
      ['1分で終わるアンケートです！', '問1。最近、睡眠は足りていますか？', '（10分経過）では最後、問48です！'],
      ['お仕事帰りですか？', '今なら無料で肌年齢を測定できるんですけど…', '（10分経過）…あ、お急ぎでした？'],
    ],
  },
  zandaka: {
    code: 12,
    behavior: 'zandaka',
    name: '通勤中の人',
    role: '改札',
    nick: 'IC残高不足の人',
    trait: '改札のレーンをふさいで「ピンポーン」。どのレーンに行くかは気まぐれ。空いたレーンを見極めろ。',
    power: 2,
    penalty: 3,
    papers: 0,
    stamp: '残高不足',
    tint: '#5b8def',
    voice: { freq: 200, type: 'triangle' },
    look: {
      skin: '#eebd98',
      hair: { style: 'side', color: '#2b2522' },
      top: { type: 'suit', color: '#4a4e57' },
      shirt: '#ffffff',
      tie: '#5b8def',
      bottom: { type: 'pants', color: '#4a4e57' },
      shoes: '#222222',
      brows: 'worried',
      cheeks: false,
      prop: { right: 'phone' },
    },
    notice: ['ピンポーン'],
    guardLines: ['ピンポーン', 'あれっ？', '残高…', 'ピンポーン（2回目）'],
    after: ['すみません…チャージしてきます'],
    talks: [['ピンポーン！', '…あ、残高不足だ。すみません、すみません…', '（後ろの人と一緒にやり直し）']],
  },
  tourist: {
    code: 13,
    behavior: 'doki',
    tune: { notice: 5, rush: 3.8, rushMax: 3, wander: 1.1 },
    name: 'トムさん',
    role: '観光客',
    nick: '道を聞く観光客',
    trait: '地図を広げてうろうろ。目が合うと「Excuse me!」と寄ってきて、道案内をすることに。',
    power: 2,
    penalty: 8,
    papers: 0,
    stamp: '道案内',
    tint: '#4bb3fd',
    voice: { freq: 300, type: 'sine' },
    look: {
      skin: '#f7dcc9',
      hair: { style: 'short', color: '#d9b25f' },
      top: { type: 'shirt', color: '#f2f2f2' },
      shirt: '#f2f2f2',
      tie: null,
      bottom: { type: 'pants', color: '#8a7a5a' },
      shoes: '#6b4a32',
      brows: 'happy',
      cheeks: true,
      width: 1.1,
      prop: { left: 'list' },
    },
    notice: ['Excuse me!', 'Hello! Sorry!', 'ちょっと、スミマセン！'],
    giveup: ['Oh…OK!', 'Thank you anyway!'],
    after: ['Thank you so much!', 'アリガトウ！'],
    talks: [
      ['Excuse me! Where is… Shibuya?', '（身ぶり手ぶりで説明する）', '（8分経過）Oh! Thank you! You are so kind!'],
      ['スミマセン、ラーメン、どこ？', '（おすすめの店を3軒、地図に書き込む）', '（8分経過）アリガトウ！'],
    ],
  },
  client_bucho: {
    code: 14,
    behavior: 'senpai',
    tune: { notice: 3.3, chase: 3.1, chaseMax: 6, lose: 9, cooldown: 12 },
    name: '権藤部長',
    role: '取引先 宣伝部長',
    nick: '話の長い取引先部長',
    trait: '取引先のえらい人。気づかれると「おお、ちょうどよかった」とゆっくり、でもしつこく追ってくる。',
    power: 4,
    penalty: 20,
    papers: 0,
    stamp: '恐縮',
    tint: '#8d6e63',
    voice: { freq: 120, type: 'triangle' },
    look: {
      skin: '#e9b995',
      hair: { style: 'slick', color: '#8b8580' },
      top: { type: 'suit', color: '#5a4636' },
      shirt: '#ffffff',
      tie: '#c0392b',
      bottom: { type: 'pants', color: '#5a4636' },
      shoes: '#1b1b1b',
      mustache: '#8b8580',
      brows: 'normal',
      cheeks: false,
      width: 1.2,
    },
    notice: ['おお、ちょうどよかった！', '君、スルスル広告さんの！', 'ちょっといいかね'],
    giveup: ['…まあ、次の打ち合わせで', '忙しそうだねえ'],
    after: ['いやあ、いい話ができた！', '次回もよろしく頼むよ'],
    talks: [
      ['おお、ちょうどよかった！', '例のCMなんだがね、社長の孫を出したいと言っていてね…', '（20分経過）…というわけで、前向きに検討頼むよ'],
      ['君のところの提案書、読んだよ', '……で、ワシの若い頃の広告というのはね', '（20分経過）いやあ、昔話が過ぎたな！'],
    ],
  },
  settai: {
    code: 15,
    behavior: 'kanji',
    name: '猪狩さん',
    role: '取引先 営業課長',
    nick: '接待好きの取引先',
    trait: '出口の前で待ち構え、「せっかくなので一杯！」と左右に揺れて通せんぼ。断るのが一番むずかしい相手。',
    power: 4,
    penalty: 25,
    papers: 0,
    stamp: '乾杯',
    tint: '#e67e22',
    voice: { freq: 240, type: 'square' },
    look: {
      skin: '#f0bf9a',
      hair: { style: 'short', color: '#2b2522' },
      top: { type: 'suit', color: '#34495e' },
      shirt: '#ffffff',
      tie: '#e67e22',
      bottom: { type: 'pants', color: '#34495e' },
      shoes: '#1b1b1b',
      brows: 'happy',
      cheeks: true,
      blush: true,
      width: 1.1,
    },
    notice: ['せっかくなので！'],
    guardLines: ['せっかくなので一杯！', '近くにいい店あるんですよ！', '一杯だけ！一杯だけ！', 'お車代は出しますから！'],
    after: ['じゃ、続きは次回！', 'いいお店、予約しときますね！'],
    talks: [
      ['せっかくなので一杯いきましょう！', '近くに焼き鳥のうまい店が…', '（25分経過）…ということで、乾杯は次回に取っておきましょう！'],
    ],
  },
  golf: {
    code: 16,
    name: '大森次長',
    role: '営業本部',
    nick: '傘ゴルフおじさん',
    trait: '閉じた傘でゴルフの素振り。構えると足元に赤い扇形が出て、振り抜いた先にいると「ナイスショット！」。構えを見たら距離を取るか、ダッシュでくぐり抜けろ。',
    power: 3,
    penalty: 8,
    papers: 0,
    stamp: 'ナイスショット',
    tint: '#2e8b57',
    voice: { freq: 140, type: 'sawtooth' },
    look: {
      skin: '#eebd98',
      hair: { style: 'slick', color: '#4a4a4a' },
      top: { type: 'vest', color: '#2e8b57' },
      shirt: '#f4f1e8',
      tie: '#c0392b',
      bottom: { type: 'pants', color: '#6b5a45' },
      shoes: '#2a1d17',
      brows: 'normal',
      cheeks: true,
      width: 1.14,
      prop: { right: 'kasa' },
    },
    notice: ['お、いいところに！', 'ちょっと見てて！', 'フォーッ！'],
    swingLines: ['ブンッ！', 'ナイスショット！', 'ファー！', 'いい当たり！'],
    after: ['日曜、コース回る？', 'スコア90切ったら教えるよ！'],
    talks: [
      ['おっと、すまんすまん！', 'ところで君、ゴルフは？ 最近ドライバーを替えてね…', '（8分経過）…インパクトの瞬間だけ意識すればいいんだよ'],
      ['ナイスショット！…あ、君に当たったか', 'いやあ、雨の日は打ちっぱなしに行けなくてね', '（8分経過）今度、練習場いっしょに行こうよ！'],
    ],
  },
  cleaner: {
    code: 17,
    name: '森さん',
    role: 'ビル管理',
    nick: '清掃員',
    trait: 'モップで床を拭きながら巡回していて、通ったあとがしばらく濡れて滑る。本人に悪気はまったくない。ぶつかっても話しかけてはこない。',
    power: 1,
    penalty: 0,
    papers: 0,
    stamp: '清掃中',
    tint: '#5dade2',
    voice: { freq: 260, type: 'triangle' },
    look: {
      skin: '#f2c6a6',
      hair: { style: 'bun', color: '#8a8580' },
      top: { type: 'shirt', color: '#5dade2' },
      shirt: '#5dade2',
      tie: null,
      bottom: { type: 'pants', color: '#2e4053' },
      shoes: '#ffffff',
      hat: { color: '#5dade2', visor: '#3b8bbf' },
      brows: 'happy',
      cheeks: true,
      prop: { right: 'mop' },
    },
    notice: ['足元お気をつけくださーい', '拭いたばっかりですよー', '滑りますよー'],
    talks: [['足元お気をつけくださーい']],
  },
  shuei: {
    code: 18,
    behavior: 'kanji',
    tune: { speed: 2.7, sense: 8 },
    name: '権田さん',
    role: '守衛',
    nick: '天気の話が長い守衛さん',
    trait: '出口の前を左右に行ったり来たり。目が合うと「いや〜よく降りますねぇ」から始まる長い天気の話。',
    power: 3,
    penalty: 14,
    papers: 0,
    stamp: '雨宿り',
    tint: '#34495e',
    voice: { freq: 120, type: 'triangle' },
    look: {
      skin: '#e3ae88',
      hair: { style: 'short', color: '#8a8580' },
      top: { type: 'suit', color: '#2c3e50' },
      shirt: '#dfe6ee',
      tie: '#1b2340',
      bottom: { type: 'pants', color: '#2c3e50' },
      shoes: '#111111',
      hat: { color: '#2c3e50', visor: '#111111', band: '#d4ac0d' },
      brows: 'happy',
      cheeks: true,
      width: 1.08,
    },
    notice: ['いや〜よく降りますねぇ'],
    guardLines: ['いや〜よく降りますねぇ', '傘、お持ちです？', '明日は晴れるらしいですよ', '台風、近づいてるんですって'],
    after: ['お気をつけて〜', '足元、滑りますからね〜'],
    talks: [
      ['いや〜よく降りますねぇ', '私が若い頃の台風はね、もっとこう…', '（14分経過）…というわけで、明日は晴れるそうですよ！'],
      ['お疲れさまです！ 傘、お持ちです？', 'この雨、梅雨前線がね、こう停滞してまして…', '（14分経過）…あ、お引き止めしちゃって！'],
    ],
  },
  // ---------------------------------------------------------------- 出張（第6章）
  mimi: {
    code: 19,
    name: '本田さん',
    role: '総務部（社員旅行の幹事）',
    nick: '地獄耳の総務',
    trait: 'スマホから目を離さないが、耳はいつもこっちを向いている。ケースの音や電話の声を聞きつけると、音のした場所まで確かめに来る。紫の輪の中では歩く音も聞こえている。止まってやり過ごせ。電話中のふりは逆効果。',
    power: 3,
    penalty: 12,
    papers: 1,
    stamp: '申請不備',
    tint: '#a05fb5',
    voice: { freq: 240, type: 'triangle' },
    look: {
      skin: '#f6d7c1',
      hair: { style: 'bob', color: '#3a2a20' },
      top: { type: 'cardigan', color: '#b58fc9' },
      shirt: '#ffffff',
      tie: null,
      bottom: { type: 'skirt', color: '#4a4e57' },
      legs: '#e9c3a5',
      shoes: '#3a2a20',
      glasses: { color: '#6b4a7a' },
      brows: 'normal',
      cheeks: false,
      scale: 0.95,
      prop: { right: 'phone' },
    },
    notice: ['見〜つけた', 'やっぱり滑川くん！', 'ちょっと、いい？'],
    heardLines: ['…ん？', '今、ガラガラって…', '誰かいるわね？'],
    voiceLines: ['…誰と電話してるの？', '声、聞こえてるわよ'],
    lostLines: ['おかしいわね…', '気のせい…？'],
    giveup: ['…逃げ足だけは速いのよね', 'まあいいわ、あとでメールする'],
    after: ['いってらっしゃい。申請はちゃんとね', '音、気をつけなさいよ'],
    talks: [
      ['あら滑川くん。出張？', 'そういえば出張申請、ハンコがひとつ足りなかったわよ', '（12分経過）…あと、領収書の宛名を「上様」にしないでね'],
      ['あら、そのケースの音。やっぱり滑川くん', '社員旅行、不参加って聞いたけど？ ここで何してるの？', '（12分経過）…まあいいわ。キャンセル料の件は、また今度'],
    ],
  },
  michizure: {
    code: 20,
    behavior: 'senpai',
    tune: { notice: 3.0, chase: 3.5, chaseMax: 6.5, lose: 10, cooldown: 10 },
    name: '横山係長',
    role: '営業3課',
    nick: '旅は道連れ係長',
    trait: 'なぜか毎回、出張先がかぶる。「隣、とっといたから！」と満面の笑みで追ってくる。悪い人ではない。ただ、2時間半ずっとしゃべるし、追いかけるのもしつこい。',
    power: 3,
    penalty: 15,
    papers: 0,
    stamp: '道連れ',
    tint: '#2e9e8f',
    voice: { freq: 220, type: 'square' },
    look: {
      skin: '#f0c4a0',
      hair: { style: 'short', color: '#3a2c24' },
      top: { type: 'suit', color: '#8e959f' },
      shirt: '#ffffff',
      tie: '#2e8b57',
      bottom: { type: 'pants', color: '#8e959f' },
      shoes: '#3a2a20',
      brows: 'happy',
      cheeks: true,
      width: 1.08,
      prop: { left: 'bag', right: 'phone' },
    },
    notice: ['おっ、滑川！', '奇遇だね〜！', 'お前もこっち？ 俺も！', '隣、とっといたから！'],
    heardLines: ['そのガラガラ、滑川でしょ！', 'お、同じケースじゃん！'],
    doorLines: ['（ガチャ）おっ、滑川！', '（ガチャ）同じ12階じゃん！'],
    giveup: ['…先に行ってるね〜', '続きは現地で！', 'あれ？ トイレかな？'],
    after: ['旅は道連れってね！', 'じゃ、また現地で！', '窓側、譲るからさ！'],
    talks: [ // S16（新幹線）。S17・S18 は stage.lines で上書きする
      ['おっ滑川！ お前も新幹線？ 俺も！', '隣の席、とっといたから！ 3列シートの真ん中だけど', '（15分経過）…で、新横浜を過ぎたら、ずっと俺のターンね'],
      ['駅弁どれにした？ 俺は迷って3つ買った', '富士山が見えるのはE席なんだよ。知ってた？', '（15分経過）…ちなみに今日は曇りで見えないらしい'],
    ],
  },
  card: {
    code: 21,
    behavior: 'kanji',
    tune: { speed: 3.8, sense: 8, cooldown: 4 },
    name: '小野さん',
    role: '空港 カード受付',
    nick: 'カード勧誘のお姉さん',
    trait: '動く歩道の降り口で、にこやかに待ち構えている。歩道は途中で降りられないので、逃げ場はない。左右に回り込んでくるので、ダッシュか電話で抜けろ。歩道の最後のマスからのダッシュなら音もしない。',
    power: 2,
    penalty: 5,
    papers: 1,
    stamp: 'ご入会',
    tint: '#e2566f',
    voice: { freq: 420, type: 'sine' },
    look: {
      skin: '#f6d3bd',
      hair: { style: 'pony', color: '#2b2522' },
      top: { type: 'vest', color: '#e2566f' },
      shirt: '#ffffff',
      ribbon: '#f2c14e',
      bottom: { type: 'skirt', color: '#2b3a67' },
      legs: '#e9c3a5',
      shoes: '#1b1b1b',
      hat: { color: '#e2566f', visor: '#2b3a67' },
      brows: 'happy',
      cheeks: true,
      scale: 0.95,
      prop: { left: 'clipboard' },
    },
    notice: ['お客様〜！'],
    guardLines: ['ただいまマイルが2倍になりま〜す', '年会費は初年度無料です〜', '3分だけお時間よろしいですか〜', 'スーツケースが当たるキャンペーン中です〜'],
    after: ['ご検討くださ〜い！', 'よいご旅行を〜！'],
    talks: [
      ['お客様〜、マイルはお貯めですか？', 'こちらのカード、ご入会いただくと今なら…', '（5分経過）…パンフレットだけでも、どうぞ〜！'],
      ['出張が多いお客様にぴったりのカードが…', '（気づけば申込書の「勤務先」欄まで書いていた）', '（5分経過）審査結果は、2週間後にご連絡しま〜す！'],
    ],
  },
  yukata: {
    code: 22,
    behavior: 'senpai',
    tune: { notice: 2.6, chase: 3.6, chaseMax: 3.5, lose: 7, cooldown: 10 },
    name: '岩田次長ご一行',
    role: '営業本部（社員旅行中）',
    nick: '部屋飲み中の社員旅行組',
    trait: 'うちの会社の社員旅行で、同じホテルに泊まっている。頭には宿のタオル。廊下で物音がするとドアを開けて顔を出し、部屋飲みに誘ってくる。夜の廊下では、ダッシュを控えめに。',
    power: 3,
    penalty: 15,
    papers: 0,
    stamp: '部屋飲み',
    tint: '#3d5a98',
    voice: { freq: 150, type: 'sawtooth' },
    look: {
      skin: '#eab08e',
      hair: { style: 'slick', color: '#6d5a4a' },
      top: { type: 'yukata', color: '#eef2f7' },
      shirt: '#2b3a67',
      tie: null,
      bottom: { type: 'skirt', color: '#eef2f7' },
      legs: '#eab08e',
      shoes: '#c9b48a',
      headband: '#f4f1ea', // 宿のタオルを頭に巻いている
      brows: 'happy',
      cheeks: true,
      blush: true,
      width: 1.15,
      prop: { right: 'can' },
    },
    // 出てくる順に見た目を変える（名前はないので、顔アイコンは yukata のまま）
    variants: [
      {},
      { look: { hair: { style: 'bald', color: '#8a8580' }, mustache: '#5a4a3a' } },
      { look: { hair: { style: 'short', color: '#2b2522' }, width: 1.05, headband: null } },
    ],
    notice: ['お、滑川くん！', '今の音、きみ？', 'おっ、若いの発見！'],
    doorLines: ['（ガチャ）…ん？', '（ガチャ）誰だ〜？', '（ガチャ）お、なんか聞こえた！'],
    giveup: ['…ま、いっか。おやすみ〜', 'あとで部屋来てね〜'],
    after: ['おやすみ〜！', '明日の朝風呂、一緒にどう？'],
    talks: [
      ['お、滑川くん！ ちょうどいい、一杯やってこうよ', '（缶ビールを手渡される）で、最近どうなの、仕事は', '（15分経過）…若い頃の出張はね、夜行バスでね…'],
      ['社員旅行、きみ来てなかったよね？ まあ入って入って', 'さっきの宴会で、部長がマイク離さなくてさ…', '（15分経過）…おっと、もうこんな時間か！'],
    ],
  },
  // ---------------------------------------------------------------- 師走（第7章）
  aisatsu: {
    code: 23,
    behavior: 'conga',
    bubble: 'aisatsu',
    name: '福田部長ほか',
    role: '得意先・縁起屋本舗',
    nick: '年末ご挨拶ご一行',
    trait: '来年のカレンダーを抱え、部下を連れてフロアを練り歩く取引先。列のどこかに触れると全員と名刺交換（人数が多いほど長い）。列はダッシュでくぐれる。電話中なら会釈して通してくれる。別のご一行と出会うと、お辞儀合戦で止まる。',
    power: 3,
    penalty: 3,
    papers: 1,
    papersLabel: 'カレンダー',
    stamp: '名刺交換',
    tint: '#f08a3b',
    voice: { freq: 200, type: 'triangle' },
    conga: { mode: 'route', members: 4, speed: 1.6, color: '#f08a3b', touch: 'talk', perMember: 2, phone: true, bow: true },
    look: {
      skin: '#eebd98',
      hair: { style: 'side', color: '#d9d4cc' },
      top: { type: 'suit', color: '#1f2a44' },
      shirt: '#ffffff',
      tie: '#c0392b',
      bottom: { type: 'pants', color: '#1f2a44' },
      shoes: '#1b1b1b',
      glasses: { color: '#8a6a10' },
      brows: 'happy',
      cheeks: true,
      width: 1.1,
      prop: { right: 'tube' },
    },
    // 2つ目のご一行は別の会社（名前つきなので顔アイコンは aisatsu_1）
    variants: [
      {},
      {
        name: '布袋課長ほか',
        role: '得意先・七福商事',
        look: {
          skin: '#f0c4a0',
          hair: { style: 'bald', color: '#6d625b' },
          top: { type: 'suit', color: '#4a3b2a' },
          shirt: '#fff8e8',
          tie: '#e8b82e',
          bottom: { type: 'pants', color: '#4a3b2a' },
          shoes: '#2a1d17',
          glasses: null,
          brows: 'happy',
          cheeks: true,
          width: 1.3,
          prop: { right: 'tube' },
        },
      },
    ],
    memberLook: { tops: [{ type: 'suit', color: '#2b3550' }, { type: 'suit', color: '#44474f' }, { type: 'suit', color: '#1f2226' }] },
    notice: ['あっ、滑川さん！', '本年も大変お世話に…！', 'ちょうどよかった！', '年末のご挨拶に〜！'],
    memberLines: ['お世話になっております〜', '（会釈）', '（名刺入れを構える）'],
    meetLines: ['いえいえこちらこそ', 'いえいえいえ', 'どうぞどうぞ', 'いやいやそちらこそ'],
    phoneLines: ['お電話中失礼しました…', '（会釈）', '（小声で）よいお年を…'],
    absorb: { leader: ['あっ、ちょうどよかった！ ご一緒に！'], member: ['あ、どうもどうも！', '（名刺入れを出しながら合流）'] },
    giveup: ['お忙しいところ失礼しました〜', 'また年始に伺います〜'],
    after: ['来年も何卒〜！', 'よいお年を〜！'],
    talks: [ // {n}=人数（巻き込んだ人も含む）、{m}=実際に減る分数。startTalk で置き換える
      ['本年も大変お世話になりました〜！', '（{n}人と、順番に名刺交換）', '（{m}分経過）来年のカレンダーです！ どうぞどうぞ！'],
      ['あっ、滑川さん！ ちょうどよかった！ ご紹介します、今年入った…', '（部下を1人ずつ紹介される。全部で{n}人）', '（{m}分経過）来年も何卒、よろしくお願いいたします〜！'],
    ],
  },
  oosouji: {
    code: 24,
    behavior: 'conga',
    bubble: 'oosouji',
    name: '捨田さん',
    role: '総務部',
    nick: '大掃除隊長',
    trait: 'マスクと軍手の大掃除隊を率いて、フロアの外周をぐるりと回る。緑の列の横か後ろから入ると最後尾にまぎれこみ、誰にも気づかれない（経理の鬼の視界も素通り）。ただし足は遅い。ダッシュで抜けられる。先頭の隊長に正面からぶつかると、掃除を頼まれる。',
    power: 2,
    penalty: 8,
    papers: 0,
    stamp: '大掃除',
    tint: '#3aa56c',
    voice: { freq: 320, type: 'sine' },
    conga: { mode: 'route', members: 4, speed: 2.8, color: '#3aa56c', touch: 'ride' },
    look: {
      skin: '#f3cfb6',
      hair: { style: 'bun', color: '#3a2c24' },
      top: { type: 'shirt', color: '#3aa56c' },
      shirt: '#3aa56c',
      tie: null,
      bottom: { type: 'pants', color: '#37474f' },
      shoes: '#ffffff',
      headband: '#ffffff',
      glasses: { color: '#5d4037' },
      brows: 'normal',
      cheeks: true,
      prop: { right: 'mop' },
    },
    memberLook: { tops: [{ type: 'shirt', color: '#dfe6d9' }, { type: 'shirt', color: '#9fc5a8' }, { type: 'cardigan', color: '#7d8f7a' }], headband: '#ffffff' },
    notice: ['はい、大掃除隊、通りまーす！', '3年使ってない物は、捨てる！', 'ときめかない物は、捨てる！', 'ホコリは上から下へ〜！'],
    memberLines: ['ホコリ多いな〜', 'マスク2重にしよ', '（雑巾をしぼる音）'],
    joinLines: ['お、手伝ってくれるの？ 助かる〜！', 'はい、1名様ご案内〜！'],
    leaveLines: ['え、もう行っちゃうの？', 'おつかれさまでーす！'],
    absorb: { leader: ['ちょうどいいところに！ これ持って！', '手が空いてる人、発見〜！'], member: ['え、ちょっ…', '（雑巾を渡された）'] },
    giveup: ['…まあいいわ、次の棚！', 'サボりは名簿にチェックね〜'],
    after: ['3年使ってない物は、捨てる！', 'はい、次の区画〜！'],
    talks: [
      ['あら、手が空いてる？ ちょうどよかった！', 'ブラインドの羽、1枚ずつ拭いてちょうだい。全部で240枚ね', '（8分経過）…はい、あと238枚！ 冗談よ、行っていいわ'],
      ['先頭に立った人は、拭き係よ！', 'エアコンのフィルター、見て！ この色！', '（8分経過）…はい、次は換気扇…あら、行っちゃうの？'],
    ],
  },
  bureiko: {
    code: 25,
    behavior: 'conga',
    bubble: 'bureiko',
    party: true,
    name: '大河原部長',
    role: '営業部長（無礼講モード）',
    nick: '無礼講部長',
    trait: 'ネクタイを頭に巻いて「今日は無礼講だ！」。部下をつなげた「二次会電車」で追ってくる。触れると最後尾に組み込まれ、奥のカラオケへ連行される。ダッシュ連打でふりほどけ。酔っているので電話中のふりは効かない。',
    power: 4,
    penalty: 15,
    papers: 0,
    stamp: '二次会',
    tint: '#c9302c',
    voice: { freq: 105, type: 'sawtooth' },
    conga: {
      mode: 'hunt', members: 3, speed: 3.5, minSpeed: 2.4, slowPerMember: 0.12, color: '#e0402f', touch: 'drag',
      presses: 4, lockT: 0.8, dragClock: 2, haulSpeed: 3.0, rest: 2.5, tangle: true,
    },
    look: null, // BOSS より後で代入する（CAST の中で BOSS を参照すると、宣言前の参照になる）
    // headband: 'tie' は「メンバー自身のネクタイを頭に巻く」指定（conga.js で置き換える）
    memberLook: { tops: [{ type: 'shirt', color: '#ffffff' }, { type: 'shirt', color: '#cfe0f5' }], headband: 'tie', blush: true, prop: { right: 'mug' } },
    notice: ['なめりかわぁ〜！', '今日は無礼講だぁ〜！', '二次会、カラオケ押さえてあるからな！', '一曲だけ！ 一曲だけ！', '二次会電車、出発進行〜！'],
    memberLines: ['カラオケ！ カラオケ！', 'よいしょ〜！', '部長〜、どこまでも〜！'],
    dragLines: ['よーし、確保〜！', 'カラオケ！ カラオケ！', '滑川、十八番なんだっけ？'],
    escapeLines: ['ちぇっ、ノリ悪いな〜', 'あれ？ 1両減った？'],
    phoneLines: ['誰と電話〜？ 代わって代わって！'],
    omiyageLines: ['お、つまみだ！ 気が利くねぇ！', '（菓子折りを開けて、全員で食べはじめた）'],
    tangleLines: ['あれ？ 先頭どこ？', '誰だ俺の肩つかんでるの', 'ぐるぐるする〜'],
    millLines: ['あれ？ 滑川どこ行った？', 'トイレか〜？'],
    lureLines: ['カラオケ！？', '割引！？ どこどこ！？'],
    absorb: { leader: ['お、お前も来い来い！', '二次会、1名様追加〜！'], member: ['え、俺も！？', 'お供しまーす！'] },
    giveup: ['…あれ、どこ行った？', 'ま、いっか！ ガハハ！'],
    after: ['二次会は始まったばかりだぞ〜！', 'よーし、次は三次会だ！'],
    talks: [ // カラオケに着いてしまったとき
      ['二次会、到着〜！', 'よーし滑川、1曲目いけ！ 十八番な！', '（15分経過）…アンコール！ アンコール！'],
      ['はい、滑川くん入りまーす！', '部長とデュエットな！ 来年はでかいコンペがあるんだ、景気づけだ！', '（15分経過）…90点！ よーし、もう1曲！'],
    ],
  },
  nencho: {
    code: 26,
    behavior: 'mtg',
    cone: '#35b7a0',
    tune: { fov: 1.3, range: 6.2, patrol: 1.7, chase: 4.0, chaseMax: 4.5, lose: 8, losLost: 1.4, cooldown: 9 },
    name: '控田さん',
    role: '総務部',
    nick: '年末調整の総務',
    trait: 'ミント色の視界でフロアを巡回。見つかると「控除証明書は！？」と走ってくる。捕まると書類を1束渡される。電話中のふりは効く。',
    power: 3,
    penalty: 12,
    papers: 1,
    stamp: '要提出',
    tint: '#35b7a0',
    voice: { freq: 430, type: 'square' },
    look: {
      skin: '#f3cfb6',
      hair: { style: 'pony', color: '#3d2b20' },
      top: { type: 'cardigan', color: '#7fd1bf' },
      shirt: '#ffffff',
      tie: null,
      bottom: { type: 'pants', color: '#2f3b45' },
      shoes: '#2b2b2b',
      glasses: { color: '#1f6b5a' },
      brows: 'normal',
      cheeks: true,
      prop: { left: 'list' },
    },
    notice: ['年末調整！！', '滑川さん！ 書類！', '控除証明書は！？', 'あっ、未提出の人！'],
    giveup: ['…デスクに置いときますからね！', '年明けでも…いや、今日中！', '（名簿の「滑川」に赤丸をつけた）'],
    after: ['今日中にお願いしますね！', 'ハンコも忘れずに！'],
    talks: [
      ['年末調整の書類、まだですよね！？', '生命保険料の控除証明書、10月にハガキで届いてますよね？ …捨てた？', '（12分経過）…じゃ、保険会社に再発行の電話を。今日中に！'],
      ['扶養控除等申告書、住所が去年のままです！', '引っ越したの、2年前ですよね？ 去年も同じこと言いましたよね？', '（12分経過）はい、ここと、ここと、ここにハンコを！'],
    ],
  },
  toikawa: {
    code: 27,
    behavior: 'doki',
    tune: { notice: 5.0, fov: 2.2, wander: 1.3, rush: 5.0, rushMax: 2.2, lose: 9, cooldown: 8 },
    name: '問川さん',
    role: '営業部 事務（旧部署）',
    nick: 'あのファイルどこ？の人',
    trait: '旧部署の事務。異動したその日から「あのファイルどこでしたっけ！？」と追いかけてくる。同じビルなので、5階まで階段で来る。目が合うと一直線に走ってくる。',
    power: 2,
    penalty: 10,
    papers: 1,
    stamp: 'ファイル捜索',
    tint: '#e67e22',
    voice: { freq: 380, type: 'triangle' },
    look: {
      skin: '#f5d3bd',
      hair: { style: 'bob', color: '#4a3020' },
      top: { type: 'cardigan', color: '#f0b27a' },
      shirt: '#ffffff',
      tie: null,
      bottom: { type: 'skirt', color: '#5a6270' },
      legs: '#d8b49a',
      shoes: '#2a2a2a',
      glasses: { color: '#8a5a3a' },
      brows: 'worried',
      cheeks: true,
      scale: 0.95,
      prop: { left: 'folder' },
    },
    notice: ['滑川さーん！', 'あのファイルどこでしたっけ！？', 'ちょっと、パスワード！'],
    kouninLines: ['後任さん！？ …じゃあ、滑川さんにも聞いときます！', 'あ、後任の方！ …滑川さーん！ ついでに！'],
    giveup: ['…自分で探します…', 'あとでチャットします！'],
    after: ['助かりました〜！', 'また聞きに来ますね！（5階まで）'],
    talks: [
      ['滑川さん！ あのファイルどこでしたっけ！？', '（共有フォルダの「最新_最終_本当に最終」を一緒に開く）', '（10分経過）…あ、デスクトップにありました！'],
      ['経費のパスワード、何でしたっけ？', '（付箋を探して、2人でキーボードの裏をのぞく）', '（10分経過）…Caps Lock入ってました！'],
    ],
  },
  fukagawa: {
    code: 28,
    behavior: 'senpai',
    orientation: 5, // 後任の淀川さんがそばを通ると、この秒数だけ新任者オリエンテーション（STAGE 23）
    tune: { notice: 4.2, chase: 3.1, chaseMax: 6, lose: 9, cooldown: 9 },
    name: '深川さん',
    role: '人事部',
    nick: '異動手続きの人事',
    trait: '異動してきた人を見つけると、手続きの書類を抱えて寄ってくる。後任の淀川さんがそばを通ると、その場で「新任者オリエンテーション」を始めてしまう（5秒）。追われているときは、淀川さんに押しつけるのもひとつの手。',
    power: 3,
    penalty: 6,
    papers: 1,
    stamp: '手続き',
    tint: '#7f8c8d',
    voice: { freq: 200, type: 'sine' },
    look: {
      skin: '#eebd98',
      hair: { style: 'neat', color: '#1b1716' },
      top: { type: 'suit', color: '#3d4452' },
      shirt: '#ffffff',
      tie: '#7f8c8d',
      bottom: { type: 'pants', color: '#3d4452' },
      shoes: '#111111',
      glasses: { color: '#1b1b1b', square: true },
      brows: 'normal',
      cheeks: false,
      scale: 1.02,
      prop: { left: 'clipboard' },
    },
    notice: ['滑川さん！ 手続き！', '異動届の件で…！', 'ちょっと、書類が！'],
    orientLines: ['おや、新任の方ですね！ では、オリエンテーションを', '社内規定の第1条から、かいつまんで…', '（ホチキス留め40ページの「新任者のしおり」を渡した）'],
    giveup: ['…では、メールで送っておきます', '（書類をそっとしまう）'],
    after: ['では、5階でもお元気で！', '（書類があと2枚あることは、言わなかった）'],
    talks: [
      ['滑川さん！ 異動の手続き、まだ3つ残ってます', '通勤経路の変更届と、内線番号の変更届と…あと座席表の写真', '（6分経過）…あ、社員証の写真、撮り直しですね。今ここで。はい、チーズ'],
      ['おや、滑川さん。5階の入館カード、もう届きました？', '届いてない？ じゃあ仮カードの申請書を。ここと、ここに署名を', '（6分経過）…はい。仮カードは、明日届きます'],
    ],
  },
  namida: {
    code: 29,
    behavior: 'senpai',
    ignorePhone: true,
    tune: { notice: 4.5, chase: 2.8, chaseMax: 9, lose: 12, cooldown: 12 },
    name: '大河原部長',
    role: '営業部長（送別モード）',
    nick: '涙もろい部長',
    trait: 'ふだんは無口な部長が、部下を送り出す日だけは号泣する。ゆっくり、しつこくついてくる。電話中のふりは「電話なんか切れよぉ〜」で効かない。',
    power: 4,
    penalty: 20,
    papers: 0,
    stamp: '号泣',
    tint: '#5d7fb3',
    voice: { freq: 105, type: 'triangle' },
    look: null, // BOSS より後で代入する
    notice: ['滑川ぁ〜〜！', '行くなよぉ〜', '5階なんて遠すぎるだろぉ〜'],
    phoneLine: ['電話なんか切れよぉ〜'],
    giveup: ['（ハンカチで鼻をかんでいる）', '…5階、遊びに行くからなぁ'],
    after: ['…よし。行ってこい！（号泣）', '（ハンカチがびしょびしょだ）'],
    talks: [
      ['滑川ぁ〜〜〜！（号泣）', 'おまえが入社した日のこと、覚えてるぞぉ…企画書が逆さまでなぁ…', '（20分経過）…新しい部署でも、スルスルやれよぉ（鼻水）'],
      ['ちょっと座れ。な？ 最後だから', '（部長の武勇伝・平成編が始まる）', '（20分経過）…エレベーターで10秒の距離だけどなぁ…さみしいなぁ…'],
    ],
  },
  okuri: {
    code: 30,
    name: '営業部のみなさん',
    role: '送別の花道係',
    nick: 'お見送り隊',
    trait: '花束贈呈のあと、フロアのあちこちで主役を待ちかまえている。近くを歩いて通ると、あなたの足あとを嗅ぎつけて1歩ずつ追ってくる。人数が増えるほど盛り上がって速くなる。追いつかれたら胴上げ。ダッシュで足あとを途切れさせれば見失う。',
    power: 3,
    penalty: 10,
    papers: 0,
    stamp: '胴上げ',
    tint: '#ff5c7a',
    voice: { freq: 300, type: 'square' },
    look: {
      skin: '#f2c9a9',
      hair: { style: 'short', color: '#2a2320' },
      top: { type: 'shirt', color: '#ffffff' },
      shirt: '#ffffff',
      tie: '#2f6db5',
      bottom: { type: 'pants', color: '#2d3240' },
      shoes: '#222222',
      brows: 'happy',
      cheeks: true,
      prop: { left: 'list' }, // 寄せ書きの色紙
    },
    // 見た目の違い（名前なしなので顔アイコンは okuri のまま）
    variants: [
      {},
      {
        look: { // 撮影係
          skin: '#f6d7c1',
          hair: { style: 'pony', color: '#5a3b28' },
          top: { type: 'cardigan', color: '#f5a3c7' },
          tie: null,
          bottom: { type: 'skirt', color: '#3e4661' },
          legs: '#d8b49a',
          shoes: '#2a2a2a',
          prop: { right: 'phone' },
        },
      },
      {
        look: {
          skin: '#e3ae88',
          hair: { style: 'side', color: '#3d2b20' },
          top: { type: 'suit', color: '#44474f' },
          shirt: '#e8f0fb',
          tie: '#e8b82e',
          bottom: { type: 'pants', color: '#44474f' },
          shoes: '#111111',
          glasses: { color: '#2b2b2b' },
          prop: {},
        },
      },
    ],
    notice: ['主役〜！', 'よっ、主役！', 'お見送りしま〜す！', 'エレベーターまでお供します！'],
    shouts: ['5階でも元気でね〜！', '最後だから言うけど、Excelのセル結合やめて〜！', '最後だから言うけど、冷蔵庫のプリン食べたの私！',
      '最後だから言うけど、ネクタイずっと曲がってた！', '5階って、エレベーターで10秒だけどね〜！', '（パチパチパチパチ）'],
    giveup: ['主役、見失った〜', '…まあ、5階だしね', 'あとでLINEしとこ'],
    after: ['いい会だった〜！', 'じゃ、B1で！'],
    talks: [
      ['主役、確保〜〜！', 'せーの！ わっしょい！ わっしょい！', '（10分経過）…天井に頭をぶつけて、やっと降ろされた'],
      ['つかまえた〜！ 最後にみんなで写真！', 'はい、もう1枚！ 次は変顔で！ 次は部署ごとに！', '（10分経過）…全42パターン、撮り終わった'],
    ],
  },
  // --- 第9章 ---------------------------------------------------------------
  yoigoshi: {
    code: 31,
    behavior: 'doki',
    tune: { notice: 5.2, fov: 2.6, wander: 1.8, rush: 5.8, rushMax: 1.5, lose: 9, cooldown: 8 },
    name: '宵越先輩',
    role: '営業局',
    nick: '寝てない自慢の先輩',
    trait: '徹夜3日目でテンションがおかしい。目が合うと猛ダッシュしてきて、寝てない自慢が始まる。',
    power: 3,
    penalty: 10,
    papers: 0,
    stamp: '寝てない自慢',
    tint: '#ff7f50',
    voice: { freq: 210, type: 'square' },
    look: {
      skin: '#eebd98',
      hair: { style: 'spiky', color: '#2a2320' },
      top: { type: 'shirt', color: '#ffffff' },
      shirt: '#ffffff',
      tie: '#e67e22',
      bottom: { type: 'pants', color: '#3b3f47' },
      shoes: '#2a1d17',
      brows: 'happy',
      cheeks: true,
      blush: true,
      width: 1.05,
      prop: { right: 'edrink' }, // エナドリ缶
    },
    notice: ['おっ滑川！寝た？俺寝てない！', '何時間寝た？俺ゼロ！', 'ハハハ！朝日がまぶしい！'],
    giveup: ['…あれ、今だれかいた？', '幻覚かな…ハハ…', '（立ったまま3秒寝た）'],
    after: ['寝たら負けだぞ！', 'よし、4日目いくか！'],
    memberLines: ['寝た？ 俺寝てない！', '何時間寝た？ 俺ゼロ！'],
    talks: [
      ['俺なんてさ、もう3日寝てないのよ', '2日目の夜がいちばんキツくてさ、3日目になると逆に冴えてくるんだよね', '（10分経過）…あれ、今って朝？夜？'],
      ['見てこれ、エナドリの空き缶タワー。今朝で20本目', '15本目で天井に届きそうになってさ、そこからが勝負なのよ', '（10分経過）…で、何の話だっけ？'],
    ],
  },
  kaeshida: {
    code: 32,
    behavior: 'yappari',
    name: '返田局長',
    role: '営業局長',
    nick: 'ちゃぶ台返し局長',
    trait: '本番直前の「やっぱりさ〜！」が口ぐせ。小さなちゃぶ台を小脇に抱え、列のいちばん後ろの仲間をねらってのしのし来る。捕まった仲間は直前修正に付き合わされる。偉い人なので、電話中のふりは効かない。',
    power: 4,
    penalty: 18,
    papers: 1,
    stamp: 'やっぱり',
    tint: '#c0392b',
    voice: { freq: 95, type: 'sawtooth' },
    look: {
      skin: '#e3ae88',
      hair: { style: 'slick', color: '#b8b2aa' },
      top: { type: 'suit', color: '#2c2f38' },
      shirt: '#ffffff',
      tie: '#c0392b',
      bottom: { type: 'pants', color: '#2c2f38' },
      shoes: '#111111',
      mustache: '#b8b2aa',
      brows: 'normal',
      cheeks: true,
      width: 1.22,
      scale: 1.03,
      prop: { left: 'chabudai' },
    },
    notice: ['やっぱりさ〜！', 'いま思ったんだけど！', 'ちょっといい？ やっぱりさ…'],
    giveup: ['…まあ、明日でいいか', '（コンペは今日だ）', '持ち帰って検討で！'],
    after: ['うん、これで良くなった', 'いい顔になってきたね', 'あとはよろしく〜'],
    memberLines: ['1枚目、やっぱり明朝体にしない？', 'その資料、やっぱり縦にしよう', '（ちゃぶ台を構えて）…全部、ひっくり返していい？'],
    talks: [
      ['やっぱりさ〜、コンセプトの"共創"なんだけど', '"協奏"のほうが響かない？ 音楽的に', '（18分経過）…うん、やっぱり元のままでいこう！'],
      ['やっぱりさ〜、全部ひっくり返していい？', '（ちゃぶ台を振りかぶって、そっと床に置いた）……表紙の青だけ。もうちょっとだけ青く', '（18分経過）…うん、さっきの青でいいや！'],
    ],
  },
  katsuta: {
    code: 33,
    behavior: 'rival',
    name: '勝田さん',
    role: 'オオテ広告 営業部',
    nick: 'ライバル代理店のエース',
    trait: 'ライバル代理店・オオテ広告のエース。チームを引き連れて悠々と歩き、すれ違いざまに仲間を引き抜いてくる。本人に触れるとマウントを取られる。',
    power: 4,
    penalty: 12,
    papers: 0,
    stamp: '勝ったな',
    tint: '#d4af37',
    voice: { freq: 170, type: 'triangle' },
    look: {
      skin: '#eebd98',
      hair: { style: 'slick', color: '#1b1716' },
      top: { type: 'suit', color: '#f4f4f0' },
      shirt: '#1b1b1f',
      tie: '#d4af37',
      bottom: { type: 'pants', color: '#f4f4f0' },
      shoes: '#1b1b1b',
      brows: 'angry',
      cheeks: false,
      scale: 1.03,
      prop: { right: 'phone' },
    },
    // オオテ広告のチーム（CAST には入れない。縁取りなし。見た目だけ）
    crew: [
      { skin: '#f0c4a0', hair: { style: 'neat', color: '#2a2320' }, top: { type: 'suit', color: '#1f2a44' }, shirt: '#ffffff', tie: '#d4af37', bottom: { type: 'pants', color: '#1f2a44' }, shoes: '#111111', brows: 'normal', prop: { left: 'folder' } },
      { skin: '#f6d7c1', hair: { style: 'bob', color: '#3d2b20' }, top: { type: 'suit', color: '#1f2a44' }, shirt: '#ffffff', tie: null, ribbon: '#d4af37', bottom: { type: 'skirt', color: '#1f2a44' }, legs: '#e0b898', shoes: '#111111', brows: 'normal', prop: { left: 'laptop' } },
      { skin: '#eebd98', hair: { style: 'short', color: '#1b1716' }, top: { type: 'suit', color: '#1f2a44' }, shirt: '#ffffff', tie: '#d4af37', bottom: { type: 'pants', color: '#1f2a44' }, shoes: '#111111', brows: 'normal', glasses: { color: '#2b2b2b' }, prop: { left: 'bag' } },
    ],
    notice: ['ふっ…', '勝ったな', 'お先に。'],
    stealLine: '{name}、でしたっけ？ うちに来ません？',
    unstealLine: '…ふっ、いい部下を持ったね',
    giveup: ['…急いでるみたいだね'],
    after: ['ま、お互い頑張りましょう。…勝ったな', 'では、結果発表で'],
    talks: [
      ['おや、スルスル広告さん。奇遇ですね', 'うちは昨日22時に完成したんで、ぐっすり8時間寝ました', '（12分経過）…顔色、大丈夫です？ …勝ったな'],
      ['あ、次ですか。先方、いい方たちですよ', 'プロジェクター、変換アダプタ要りますよ。うちは3種類持ってきたんで', '（12分経過）…あ、貸しませんけどね。勝ったな'],
    ],
  },
  natori: {
    code: 34,
    behavior: 'kanji',
    tune: { speed: 2.8, sense: 7, cooldown: 4 },
    name: '名取さん',
    role: 'ビッグクライアント 総務部',
    nick: 'セキュリティに厳しい会場係',
    trait: '先方の総務部の若手。会場の扉の前を左右に動いて通せんぼ。捕まると、連れている人数分の入館証チェックと、スマホのカメラにシール貼りが始まる。',
    power: 3,
    penalty: 3,
    perMember: 2,
    papers: 0,
    stamp: 'セキュリティ',
    tint: '#3b82c4',
    voice: { freq: 330, type: 'sine' },
    look: {
      skin: '#f6d7c1',
      hair: { style: 'bob', color: '#3d2b20' },
      top: { type: 'suit', color: '#2f3a55' },
      shirt: '#ffffff',
      tie: null,
      ribbon: '#3b82c4',
      bottom: { type: 'skirt', color: '#2f3a55' },
      legs: '#e0b898',
      shoes: '#1b1b1b',
      brows: 'happy',
      cheeks: true,
      scale: 0.97,
      prop: { left: 'clipboard' },
    },
    notice: ['お待ちください〜！'],
    guardLines: ['入館証を拝見します！', '皆さまの分も！', 'カメラにシールを！', '撮影はご遠慮ください！'],
    after: ['では、ご案内いたします！', 'シール、剥がさないでくださいね！'],
    memberLines: ['入館証を拝見します！', '（シールを貼っている）'],
    checkSelf: '（入館証を見せた。…顔写真と3回見比べられた）',
    checkMember: '（{name}のスマホのカメラにシールを貼っている）',
    talks: [
      ['本日はお越しいただきありがとうございます。会場に入る前に、セキュリティチェックを', '（入館チェック）', '（{N}分経過）…はい、全員のカメラにシールを貼りました。剥がすと警報が鳴ります'],
      ['会場係の名取と申します！ 皆さまの入館証を拝見します', '（入館チェック）', '（{N}分経過）…あ、お一人、入館証が上下逆でした。付け直しますね'],
    ],
  },
};
export const BOSS = {
  name: '大河原部長',
  role: '営業部長',
  tint: '#1b2340',
  voice: { freq: 110, type: 'triangle' },
  look: {
    skin: '#e9b995',
    hair: { style: 'bald', color: '#8b8580' },
    top: { type: 'suit', color: '#3b3f47' },
    shirt: '#ffffff',
    tie: '#8a1f2b',
    bottom: { type: 'pants', color: '#3b3f47' },
    shoes: '#111111',
    glasses: { color: '#6b5a2a' },
    mustache: '#6d6660',
    brows: 'normal',
    width: 1.25,
    scale: 1.05,
  },
  lines: ['おう、企画書か。', '……うん。いいじゃない。', 'これで行こう。承認！'],
  stamp: '承認',
};

// 無礼講部長は、部長の見た目にネクタイの鉢巻き（CAST の中では BOSS をまだ参照できない）
CAST.bureiko.look = { ...BOSS.look, tie: null, headband: '#8a1f2b', blush: true, brows: 'happy', cheeks: true, prop: { right: 'mug' } };
// 涙もろい部長は、部長の見た目にハンカチ
CAST.namida.look = { ...BOSS.look, brows: 'worried', blush: true, prop: { right: 'hankie' } };
// カラオケ割引券に群がる宴会好き
CAST.kanji.party = true;
CAST.settai.party = true;

// ゴールにいる人（部長席・経理の鬼の席）
export const GOAL_NPC = {
  boss: { ...BOSS, nick: '営業部長' },
  keiri: {
    name: '細田さん',
    role: '経理部',
    nick: '経理の鬼',
    tint: '#e0402f',
    voice: { freq: 540, type: 'square' },
    look: null,
    lines: ['……経費精算ですね。', '（領収書を1枚ずつ、電卓を叩きながら確認している）', '……不備なし。受理します。'],
    stamp: '受理',
  },
};

export const WORKER_HAIR = ['short', 'side', 'bob', 'long', 'short', 'bald', 'pony', 'neat'];
export const HAIR_COLORS = ['#2a2320', '#3d2b20', '#1b1716', '#5a3b28', '#6d5a4a', '#8a8580', '#2c2420'];
export const SKINS = ['#f2c9a9', '#eebd98', '#f6d7c1', '#e3ae88', '#f0c4a0'];
export const WORKER_TOPS = [
  { type: 'suit', color: '#2f3a55' },
  { type: 'suit', color: '#44474f' },
  { type: 'shirt', color: '#ffffff' },
  { type: 'shirt', color: '#cfe0f5' },
  { type: 'cardigan', color: '#c9b79c' },
  { type: 'cardigan', color: '#7d8f7a' },
  { type: 'shirt', color: '#f5d8d8' },
  { type: 'suit', color: '#1f2226' },
];

GOAL_NPC.keiri.look = CAST.keiri.look;

// ハンコラリーの決裁者
GOAL_NPC.kacho = {
  name: '黒木課長',
  role: '企画部',
  nick: '課長',
  tint: '#ffcf3a',
  voice: { freq: 130, type: 'triangle' },
  look: CAST.mtg.look,
  lines: ['お、稟議書ね。…ついでに30分だけMTG…', '…いや、今日はハンコだけね。（読まずに押す）', 'はい、ポン。次は部長ね。'],
  stamp: '課長印',
};
GOAL_NPC.jomu = {
  name: '亀山常務',
  role: '常務取締役',
  nick: '常務',
  tint: '#7a5ea8',
  voice: { freq: 90, type: 'sawtooth' },
  look: {
    skin: '#e6b48f',
    hair: { style: 'bald', color: '#f0ece6' },
    top: { type: 'suit', color: '#3a2f4f' },
    shirt: '#ffffff',
    tie: '#7a5ea8',
    bottom: { type: 'pants', color: '#3a2f4f' },
    shoes: '#111111',
    glasses: { color: '#c9a227' },
    brows: 'normal',
    width: 1.15,
    scale: 1.02,
  },
  lines: ['……うむ。稟議書か。', '（ハンコを探して、引き出しを全部開けている）', 'あった。ポン。…お辞儀ハンコにしといたよ。'],
  stamp: '常務印',
};
GOAL_NPC.boss.rallyLines = ['稟議か。どれどれ。', '課長のハンコ、ちょっと傾いてない？…まあいいか。', 'ポン。常務は午後いないから急いで。'];

// 第8章：異動先の室長と、引き継ぎの報告を受ける部長
GOAL_NPC.shitsucho = {
  name: '熱海室長',
  role: '特命プロジェクト室 室長',
  nick: '室長',
  tint: '#1f4e79',
  voice: { freq: 150, type: 'sawtooth' },
  look: {
    skin: '#e9b995',
    hair: { style: 'slick', color: '#1b1716' },
    top: { type: 'shirt', color: '#ffffff' },
    shirt: '#ffffff',
    tie: '#1f4e79',
    suspenders: '#1f4e79',
    bottom: { type: 'pants', color: '#2d3240' },
    shoes: '#111111',
    glasses: { color: '#1b1b1b', square: true },
    brows: 'normal',
    cheeks: true,
    width: 1.1,
    scale: 1.04,
  },
  lines: ['おっ、来たな滑川！ 特命プロジェクト室へようこそ！', '（段ボールが次々と運び込まれてくる）', 'さっそくだが…でかいコンペが来る。君の“スルスル”、頼りにしてるぞ。'],
  stamp: '着任',
};
GOAL_NPC.handover = {
  ...BOSS,
  nick: '営業部長',
  lines: ['おう、引き継ぎ終わったか。', '（淀川さんが、メモ帳3冊と「新任者のしおり」を差し出している）', '……滑川より、ちゃんとしてるな。今夜の送別会、主役なんだから遅れるなよ！'],
  stamp: '引継完了',
};

GOAL_NPC.judge = {
  name: '鶴田社長',
  role: '社内コンペ 審査員長',
  nick: '審査員長',
  tint: '#d4a82a',
  voice: { freq: 100, type: 'sawtooth' },
  look: CAST.shacho.look,
  lines: ['来たか。では、始めたまえ。', '（プレゼン中……スライドが1枚、逆さまだった）', '……ふむ。面白い。採用だ！'],
  stamp: '採用',
};

// コピー機
export const COPIER = {
  jammed: ['ピー……紙詰まりです', '「トレイ2を確認してください」', 'ガガッ……（紙を噛んでいる）', '「トナーが切れました」'],
  start: 'よし、動いた！印刷開始…',
  done: '印刷完了！会議室へ！',
};

// 順番を飛ばしたとき
export const RALLY_REJECT = {
  boss: ['お、稟議？…課長のハンコがまだだね。', '先に課長にもらってきてくれる？'],
  jomu: ['……ん？部長のハンコがないね。', '順番、大事だよ。'],
  kacho: ['もう押したよ？次、行っといで。'],
};

// 味方：エース新人（見つけると一度だけ身代わりになってくれる）
export const ALLY = {
  name: '早瀬くん',
  role: '営業部 新人',
  nick: 'エース新人',
  trait: 'フロアのどこかにいる期待の新人。話しかけると仲間になり、捕まりそうなときに一度だけ身代わりになってくれる。',
  tint: '#2fb3c9',
  look: {
    skin: '#f3cdb2',
    hair: { style: 'slick', color: '#2a1f1a' },
    top: { type: 'suit', color: '#1f4e79' },
    shirt: '#ffffff',
    tie: '#2fb3c9',
    bottom: { type: 'pants', color: '#1f4e79' },
    shoes: '#1a1a1a',
    brows: 'normal',
    cheeks: true,
    scale: 0.95,
    prop: { left: 'notebook' },
  },
  waiting: ['先輩！お供します！', '先輩、今どちらへ？', 'お手伝いできること、ありますか！'],
  join: ['お供します！何かあったら任せてください！', '先輩の背中、見て学びます！'],
  intercept: ['先輩は今忙しいので！僕が伺います！', 'その件、僕がお聞きします！', '先輩！ここは僕に任せて！'],
  reaction: ['お、君は新人の…じゃあ君に話そう', 'ほう、元気がいいね。聞いてくれる？', '……じゃあ、あなたに説明します'],
};

// 第8章の同行者（名簿には載らない）：後任の淀川さんと、台車の押尾さん
export const SUCCESSOR = {
  name: '淀川さん',
  role: '営業部（4月から）',
  nick: '年上の後任',
  trait: '滑川の後任。前職は銀行員（勤続20年）。とにかく律儀で、あなたの足あとを1歩ずつたどり、すれ違う人全員にあいさつする。走れない。',
  tint: '#4b8fd6',
  voice: { freq: 150, type: 'triangle' },
  look: {
    skin: '#eebd98',
    hair: { style: 'side', color: '#8a8580' },
    top: { type: 'suit', color: '#2c3e66' },
    shirt: '#ffffff',
    tie: '#8a9bb0',
    bottom: { type: 'pants', color: '#2c3e66' },
    shoes: '#1a1a1a',
    glasses: { color: '#6d6660' },
    brows: 'worried',
    cheeks: true,
    width: 1.05,
    prop: { left: 'notebook', right: 'redpen' },
  },
  hello: ['よろしくお願いいたします（メモ帳を開く）'],
  idle: ['今の、メモしてもよろしいですか', '「ちょっといい？」…と。メモしました', '御行…あ、御社では…'], // 8〜12秒ごと
  lag: ['滑川さ〜ん、待ってくださ〜い', 'あの…どちらへ…？'], // 5m以上遅れたとき
  greet: ['後任の淀川と申します。よろしくお願いいたします', '（名刺を両手で差し出した）', '滑川の後任で参りました、淀川です'],
  quiet: ['（会釈）', '（小声で）後任の淀川です…'], // 電話中・傘の間
  orient: ['は、はい…第1条から…', '（しおりにメモを取っている）', '（しおりの40ページ目に付箋を貼った）'],
  goal: ['（メモ帳を閉じて、深々とお辞儀）'],
};
// 淀川さんにあいさつされた人の反応（kouninLines がない人）
export const KOUNIN_REACT = ['お、滑川の後任？ …ってことは、滑川もいる？', 'あ、どうもどうも。…滑川〜！ ちょっといい？', '後任さん？ じゃあ引き継ぎ漏れ、滑川に言っとこ'];
export const DAISHA = {
  name: '押尾さん',
  role: '引っ越し業者',
  nick: '台車の人',
  trait: '段ボールを積んだ台車で、あなたの足あとをたどってくる。後ろから追ってくる人は台車でドーン。来た道を引き返すと、あなたもひかれる。',
  tint: '#2f6db5',
  look: {
    skin: '#e3ae88',
    hair: { style: 'short', color: '#2a2320' },
    top: { type: 'shirt', color: '#2f6db5' },
    shirt: '#2f6db5',
    tie: null,
    bottom: { type: 'pants', color: '#1f4f7a' },
    shoes: '#ffffff',
    hat: { color: '#2f6db5', visor: '#1b2340' },
    brows: 'happy',
    cheeks: true,
    width: 1.1,
  },
  hello: ['先導、お願いしまーす！'],
  move: ['台車通りまーす！', 'はいはい、ごめんなさいよー！', '足元失礼しまーす！'], // 動いているとき4〜6秒ごと
  bump: ['あぶなーい！', 'バックはやめてー！'],
  blocked: ['あれ、段ボール増えてません？'],
  hit: ['うわっ、台車！', 'いてて…段ボールが…', '（中身は割り箸だった）'], // はね飛ばされた人の吹き出し
};

// 第9章：審査員長（取引先の権藤部長）
GOAL_NPC.gondo = {
  name: '権藤部長',
  role: 'ビッグクライアント 宣伝部長（審査員長）',
  nick: '審査員長',
  tint: '#8d6e63',
  voice: { freq: 120, type: 'triangle' },
  look: CAST.client_bucho.look,
  lines: ['……では、スルスル広告さんの提案は以上ですね。', '（権藤部長が、資料をゆっくり閉じた。……今日は、昔話をしなかった）', '……ふむ。結果は、追ってご連絡します。'],
  stamp: '提案完了',
};

// 第9章：特命プロジェクト室のチーム（CAST には入れない。早瀬くんと同じ扱い）
export const TEAM = {
  mamiya: {
    name: '間宮さん',
    role: '特命プロジェクト室 デザイナー（クリエイティブ局から異動）',
    portrait: 'team_mamiya',
    look: {
      skin: '#f2c9a9',
      hair: { style: 'long', color: '#1b1716' },
      top: { type: 'shirt', color: '#2b2b2b' },
      shirt: '#2b2b2b',
      tie: null,
      bottom: { type: 'pants', color: '#4a4e57' },
      shoes: '#f2f2f2',
      glasses: { color: '#2b2b2b', square: true },
      brows: 'worried',
      cheeks: false,
      prop: { left: 'laptop' },
    },
    sleep: ['…あと1ピクセル…右…', '…そのフォント…ちがう…'],
    wake: ['寝てない寝てない！ …1ピクセル、右に寄せました', 'はっ！保存した！？'],
    caught: ['あ、デザインの件ですか…？'],
    left: ['滑川さ〜ん！', '先に行っててください〜！'],
    back: ['すみません！', '助かりました！'],
    stolen: ['え…御社、Mac支給ですか…？'],
    unstolen: ['やっぱり戻ります！（うちもMacでした）'],
  },
  wakaba: {
    name: '若葉くん',
    role: '特命プロジェクト室（兼務・営業部 新人）',
    portrait: 'shinjin',
    look: CAST.shinjin.look,
    sleep: ['…せんぱ〜い…むにゃ', '…メモ…とりました…'],
    wake: ['はっ！せんぱ〜い！おはようございます！', 'メモ取らせてください！'],
    caught: ['せんぱ〜い！助けてくださ〜い！'],
    left: ['せんぱ〜い！待ってくださ〜い！'],
    back: ['せんぱ〜い！一生ついていきます！'],
    stolen: ['え、研修制度が充実してるんですか…？'],
    unstolen: ['やっぱり滑川先輩についていきます！'],
  },
  mikami: {
    name: '三上さん',
    role: '特命プロジェクト室（兼務・営業2課 同期）',
    portrait: 'doki',
    look: CAST.doki.look,
    sleep: ['…充電器…貸して…', '…タイプC…むにゃ…'],
    wake: ['はっ！…スマホ、充電0%！', '寝てない寝てない！'],
    caught: ['えっ、私！？'],
    left: ['滑川く〜ん！', '先行ってて〜！…いや待って！'],
    back: ['ごめん！', '助かった〜！'],
    stolen: ['え…福利厚生の話だけ聞いても…？'],
    unstolen: ['やっぱり戻ります！（福利厚生は聞けた）'],
  },
};
export const TEAM_PHONE_WAKE = ['はっ！先方からですか！？', '（着信音で飛び起きた）'];
